core/urls.py
from django.urls import path
from core.views import  account,historial,traductor,edit, videocamara
app_name = "core"
urlpatterns = []
 
urlpatterns += [
    path('registrar/', account.register, name='registrar'),
    path('salir/', account.Salir, name='salir'), 
]

urlpatterns += [
        path('historial/', historial.list_historial.as_view(), name='historial'),
        path('historial/delete/<int:pk>/', historial.historial_delete, name='historial_delete'),
        path('historial/clear/', historial.clear_historial.as_view(), name='clear_historial'),
        path('historial/save_word', historial.save_word, name='save_word'),
]

urlpatterns += [
        path('inicio/', traductor.mostrar_html, name='inicio'),
        path('text_speech', traductor.text_speech, name='text_speech'), 
]

    
urlpatterns += [
        path('editar/', edit.edit_user, name='editar'), 
]

urlpatterns += [
    path('video_feed', videocamara.video_feed, name='video_feed'),
    path('start_camera', videocamara.start_camera, name='start_camera'),
    path('stop_camera', videocamara.stop_camera, name='stop_camera'),
]

traductor/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

from core.views import account


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', account.signin, name='login'),
    path('core/',include('core.urls',namespace="core") ),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from traductor import utils

class User(AbstractUser):
    image = models.ImageField(
        verbose_name='Archivo de imagen',
        upload_to='users',
        max_length=1024,
        blank=True,
        null=True
    )

    class Meta:
        verbose_name = "Usuario"
        verbose_name_plural = "Usuarios"

    def get_image_url(self):
        return utils.get_image(self.image)


class Historial(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    word = models.CharField(max_length=255)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user} - {self.word} - {self.date.strftime('%Y-%m-%d %H:%M')}"

core/views/historial.py
from django.views.generic import ListView,View
from django.db.models import Q

from django.urls import reverse_lazy

from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
import json

from django.shortcuts import get_object_or_404, redirect,render
from django.http import HttpResponseForbidden,HttpResponseRedirect

from core.models import Historial

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required


class list_historial(LoginRequiredMixin,ListView):
    model = Historial
    template_name = 'Historial.html'
    paginate_by= 5
    context_object_name = 'palabras'
    login_url = '/'

    def get_queryset(self):
        queryset = super().get_queryset()
        usuario = self.request.user  
        palabra = self.request.GET.get('palabra')

        query = Q(user=usuario)
        if palabra:
            query &= Q(word__icontains=palabra)
        
        return queryset.filter(query).order_by('id')
        
@login_required
def historial_delete(request, pk):
    palabra = get_object_or_404(Historial, pk=pk)

    if palabra.user != request.user:
        return HttpResponseForbidden()

    palabra.delete()
    return redirect('core:historial')

class clear_historial(LoginRequiredMixin, View):
    template_name = 'clean_historial.html'
    success_url = reverse_lazy('core:historial')
    login_url = '/'

    def get(self, request, *args, **kwargs):
        context = {
            'grabar': 'Eliminar historial',
            'description': '¿Esta seguro de eliminar el historial?',
            'back_url': self.success_url,
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        user_historial = Historial.objects.filter(user=request.user)
        user_historial.delete()
        return HttpResponseRedirect(self.success_url)
    

@login_required
def save_word(request):
    if request.method == 'POST':
        try:
            
            user= request.user
            
            data = json.loads(request.body)
            
            word = data.get('word', None)
                        
            nueva_palabra = Historial(user=user, word=word)
            nueva_palabra.save()
            
            return JsonResponse({'message': 'Palabra guardada correctamente.'}, status=200)
        
        except Exception as e:
            return JsonResponse({'error': str(e)}, status=400)
    
    return redirect('core:inicio')
    

templates/Base_form.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <link rel="stylesheet" href="{% static 'css/inicio.css' %}">
    <link rel="stylesheet" href="{% static 'css/historial.css' %}">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/5.3.0/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css" rel="stylesheet">
    <link rel="icon" href="{% static 'img/engranaje.ico' %}" type="image/x-icon">
    <title>MAR Translator</title>
</head>
<body>
        {% if user.is_authenticated %}
        <nav class="">
            <div class="Menu-options">
                <div class="user-info">
                    <img src="{{user.get_image_url}}" alt="Imagen de perfil">
                </div>
                <span class="link-create"> {{user.username}}</span>
                <a href="{% url 'core:inicio' %}" class="link-create">  Traductor </a>
                <a href="{% url 'core:historial' %}" class="link-create">  Mi Historial</a>
                <a href="{% url 'core:editar' %}" class="link-create">  Editar Perfil</a>
                <a href="{% url 'core:salir' %}" class="link-create">  Cerrar Sesion</a>
            </div>
        </nav>
        {% else %}
            <nav class="">
                <div class="Menu-options">
                    <a href="{% url enlace %}" class="link-create">{{ options }}</a>
                </div>
            </nav>
        {% endif %}

        {% block content %}
        {% endblock %}

        {% block Formulario_content %}
        {% endblock  %}


   
    


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>

</html>

templates/Historial.html
{% extends 'Base_form.html' %}
{% block content %}
    <div id="container3" class="container">
        <!-- Agregar campo de búsqueda -->
        <form action="">
            <div class="input-group">
                <input type="text" id="searchInput" class="form-control" placeholder="Buscar por palabra" name="palabra" value="{{ request.GET.palabra }}">
            </div>
            <div class="botones2">
            <button id="boton3" class="envio" type="submit">Buscar</button>
            <a href="{% url 'core:clear_historial' %}" id="boton4" class="envio">Limpiar</a>

            </div>
        </form>
    </div>

    <div id="container3" class="container">
        <ul id="word-list">
            {% for p in palabras %}
            <li class="word-item">
                <span>{{p.word}}</span><span class="timestamp">{{p.date}}</span>
                <a class="text-dark" href="{% url 'core:historial_delete' p.id %}" id="botondelete" data-bs-toggle="tooltip" data-bs-title="Eliminar palabra"><i class="bi bi-trash-fill"></i></a>
            </li>
            {% endfor%} 
        </ul>
    </div>

    {% if is_paginated %}
       <div class="card-footer">
         <nav aria-label="Demo of disable class">
            <ul class="pagination justify-content-center flex-wrap">
               {% if page_obj.has_previous %}
                  <li class="page-item">
                     <a
                        href="?page={{ page_obj.previous_page_number }}{{ to_paginate_query }}"
                        class="page-link text-primary fw-bolder"
                     >
                        &laquo; Atrás
                     </a>
                  </li>

                  <li class="page-item">
                     <a href="?page=1{{ to_paginate_query }}" class="page-link text-primary fw-bolder">Inicio</a>
                  </li>
               {% else %}
                  <li class="page-item disabled" style="pointer-events:none; line-height: 1.5">
                     <a class="page-link bg-secondary bg-opacity-10">&laquo; Atrás</a>
                  </li>
                  <li class="page-item disabled" style="pointer-events:none">
                     <a href="#" class="page-link bg-secondary bg-opacity-10">Inicio</a>
                  </li>
               {% endif %}

               {% for index_paginate in paginator.page_range %}
                  {% if index_paginate <= page_obj.number|add:8 and index_paginate >= page_obj.number|add:-8 %}
                     {% if page_obj.number == index_paginate %}
                        <li class="page-item active" style="pointer-events:none">
                           <a href="#" class="page-link text-dark fw-bolder">{{ forloop.counter }}</a>
                        </li>
                     {% else %}
                        <li class="page-item">
                           <a href="?page={{ forloop.counter }}{{ to_paginate_query }}"
                              class="page-link text-dark-opacity-5">{{ forloop.counter }}</a>
                        </li>
                     {% endif %}
                  {% endif %}
               {% endfor %}

               {% if page_obj.has_next %}
                  <li class="page-item">
                     <a
                        href="?page={{ page_obj.paginator.num_pages }}{{ to_paginate_query }}"
                        class="page-link text-primary"
                     >
                        Final {{ paginator.page_range.stop|add:-1 }}
                     </a>
                  </li>

                  <li class="page-item">
                     <a href="?page={{ page_obj.next_page_number }}{{ to_paginate_query }}"
                        class="page-link text-primary">Siguiente &raquo;</a>
                  </li>
               {% else %}
                  <li class="page-item disabled text-primary" style="pointer-events:none">
                     <a href="#" class="page-link bg-secondary bg-opacity-10 text-primary">Final</a>
                  </li>
                  <li class="page-item disabled" style="pointer-events:none">
                     <a class="page-link bg-secondary bg-opacity-10 text-primary">Siguiente &raquo;</a>
                  </li>
               {% endif %}
            </ul>
         </nav>
       </div>
      {% endif %}   
 {% endblock %}

templates/clean_historial.html
{% extends 'Base_form.html' %}
{% block content %}
    <div class="container mt-5">
        <div class="header text-center">
            <h3>{{description}}</h3>
        </div>
        <div class="body text-center mt-4">
            <h2>Una vez eliminado no hay marcha atrás.</h2>
        </div>
        <div class="footer text-center mt-4">
            <form method="POST" action="">
                {% csrf_token %}
                <div class="botones2">
                <button class="" id="clear" type="submit">
                    <i class="bi bi-x-circle-fill"></i> Eliminar
                </button>
                <a class="" id="noclear" href="{{back_url}}">
                    <i class="bi bi-arrow-left-square-fill"></i> Cancelar
                </a>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/editperfil.html
{% extends 'Base_form.html' %}
    {% load static %}
{% block content %}
    <div id='container1' class="container">
        <h2>Editar Usuario</h2>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="profile-picture" style="margin-bottom: 20px; margin-top: 20px; text-align: center;">
                <img src="{{ user.get_image_url }}" alt="Imagen de perfil" id="imgperfil">
        </div>
        <div>
            <label for="id_image">Imagen:</label>
            <input type="file" id="id_image" name="image" value="" onchange="temporalimg(event)">
        </div>
        <div>
            <label for="id_first_name">Nombre:</label>
            <input type="text" id="id_first_name" name="first_name" value="{{ user.first_name }}">
        </div>
        <div>
            <label for="id_last_name">Apellido:</label>
            <input type="text" id="id_last_name" name="last_name" value="{{ user.last_name }}">
        </div>
        <div>
            <label for="id_email">Email:</label>
            <input type="email" id="id_email" name="email" value="{{ user.email }}">
        </div>
        <div>
            <label for="id_current_password">Contraseña Actual:</label>
            <input type="password" id="id_current_password" name="current_password">
            {% if messages %}
                {% for message in messages %}
                    <p style="color: red;">{{ message }}</p>
                {% endfor %}
            {% endif %}
        </div>
        <div>
            <label for="id_new_password">Nueva Contraseña:</label>
            <input type="password" id="id_new_password" name="new_password">
        </div>
        <div>
            <button type="submit">Guardar Cambios</button>
        </div>
    </form>
    </div>
    <script src="/static/js/imgtemporal.js"></script>
 {% endblock %}

templates/home.html
{% extends 'Base_form.html' %}
{% block content %}
        {% load static %}
        <div id="container2" class="container">
            <div class="container-capture">
                <img id="video" width="640" height="480" autoplay></img>
            </div>
            <div class="botones">
            <button id="start" onclick="startVideo()">Iniciar</button>
            <button id="boton1" onclick="stopVideo()" style="display: none;" class="envio" type="submit">Detener</button>
            <button id="clean" >Limpiar</button>
            </div>
            <form>
                <div class="form-group">
                    <label for="email">Texto Traducido:</label>
                    <div class="cuadro" style="position: relative;">
                        <input id="cuadro_texto" name="traducido" placeholder="El Texto se mostrara aqui" required>
                        <a id="volumeButton" ><i class="bi bi-volume-up-fill"></i></a>
                    </div>
                </div>

            </form>
        </div>
        <script src="/static/js/fetch.js"></script>
        <script src="/static/js/captura.js"></script>
        <script src="/static/js/save_word.js"></script>
        <script>
            document.getElementById('clean').addEventListener('click', function() {
                document.getElementById('cuadro_texto').value = '';
            });
        </script>
        <script src="/static/js/text_to_speech.js"></script>
{% endblock %}

templates/login.html
{% extends "Base_form.html" %}

{% block Formulario_content %}
{% load crispy_forms_tags %}

<div id="container1" class="container">
  <p>{{error}}</p>
  <h2>Formulario de inicio de sesión</h2>
  <br />
  
  <form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button  type="submit" class="btn btn-danger">iniciar sesion</button>
  </form>
</div>
{% endblock %}

templates/signup.html
{% extends "Base_form.html" %}

{% block Formulario_content %}
{% load crispy_forms_tags %}
    <div id="container1" class="container">
        {{error}}
        <h2>Creacion de cuenta</h2> 
        <form method="post" action="{% url 'core:registrar' %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="email">Nombres:</label>
                <input type="text" id="nombres" name="nombres" placeholder="Ingrese sus nombres" required>
            </div>
            <div class="form-group">
                <label for="password">Apellidos:</label>
                <input type="text" id="apellidos" name="apellidos" placeholder="Ingrese sus apellidos" required>
            </div>
            <div class="form-group">
                <label for="email">Correo electrónico:</label>
                <input type="email" id="email" name="email" placeholder="Ingrese su correo electrónico"  required>
            </div>
            <div class="form-group">
                <label for="password">Contraseña:</label>
                <input type="password" id="password" name="password1" placeholder="Ingrese su contraseña" pattern="(?=.*[a-zA-Z])(?=.*\d).{8,}" title="La contraseña debe tener al menos 8 caracteres, incluir al menos una letra y al menos un número" required>
            </div>
            <div class="form-group">
                <label for="password">Verificar contraseña:</label>
                <input type="password" id="password2" name="password2" placeholder="Vuelva a ingresar su contraseña" pattern="(?=.*[a-zA-Z])(?=.*\d).{8,}" title="La contraseña debe tener al menos 8 caracteres, incluir al menos una letra y al menos un número" required>
            </div>
            
            <button class="envio" type="submit">Registrar</button>
        </form>
        
    </div>
    
{% endblock %}